routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// if (env('APP_ENV') === 'production') {
//     URL::forceScheme('https');
// }

// Auth::routes();
Route::get('/hidden/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/hidden/login', 'Auth\LoginController@login');
Route::post('/hidden/logout', 'Auth\LoginController@logout')->name('logout');

// test
Route::get('/notifemaile', 'NotifController@test')->name('notifemaile');

// real
Route::get('/notifemail', 'NotifController@index')->name('notifemail');

Route::get('/', 'FrontendController@index')->name('main');
Route::get('/file/{id}/{slug}', 'FrontendController@download')->name('download');
Route::post('/pesan', 'FrontendController@store_pesan')->name('pesanstore');
Route::get('/berita', 'FrontendController@berita')->name('berita');
Route::get('/album', 'FrontendController@album')->name('album');
Route::get('/faq', 'FrontendController@faq')->name('faq');
Route::get('/kontak', 'FrontendController@kontak')->name('kontak');
Route::get('/rekening', 'FrontendController@rekening')->name('rekening');
Route::get('/detail_berita/{slug_title}', 'FrontendController@detailberita')->name('detail_berita');
Route::get('/kategori_berita/{katber_slug}', 'FrontendController@kategori')->name('kategori_berita');
Route::get('/detail_album/{album_slug}', 'FrontendController@detailalbum')->name('detail_album');
Route::get('/tentang-kami', 'FrontendController@tentangkami')->name('tentangkami');
Route::get('/detail_tentang/{katbout_slug}', 'FrontendController@detailtentang')->name('detail_tentang');
Route::post('/detail-donasi/confirm', 'FrontendController@detaildonasi')->name('detail-donasi');
Route::get('/status-donasi/{kode_donasi}', 'FrontendController@statusdonasi')->name('status-donasi');
Route::get('/cek-donasi', 'FrontendController@cekdonasi')->name('cek-donasi');
Route::put('/konfirmasi-donasi/{kode_donasi}', 'FrontendController@konfirmasidonasi')->name('konfirmasi-donasi');
Route::get('/list-donatur', 'FrontendController@listdonatur')->name('listdonatur');
Route::get('/manual-payment/{rekening_slug}', 'FrontendController@manualpembayaran')->name('manual-payment');

// Zakat
Route::get('/zakat', 'FrontendController@zakat')->name('zakat');

// Midtrans
Route::post('/finish', function () {
    return redirect()->route('/');
})->name('donasi.finish');

Route::post('/donasi/store', 'FrontendController@submit')->name('donasi.store');
Route::post('/zakat/store', 'FrontendController@submitzakat')->name('zakat.store');
Route::post('/notification/handler', 'FrontendController@notificationHandler')->name('notification.handler');

// AJAX
Route::post('/jenis_change', 'FrontendController@jenis')->name('front.jenis');

// Filemanager
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

// My Routes
Route::group(['namespace' => 'Admin',  'prefix' => 'hidden', 'middleware' => 'auth'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/', 'DashboardController@index')->name('home');

        // Account
        Route::get('/profil', 'AkunController@index')->name('profil.index');
        Route::put('/profil', 'AkunController@update')->name('profil.update');
        Route::resource('/manajemen_akun', 'ManukController');

        // Setting
        Route::get('/setting_zakat', 'SettingzakatController@index')->name('settingzakat.index');
        Route::put('/setting_zakat', 'SettingzakatController@update')->name('settingzakat.update');

        // Setting
        Route::get('/settings', 'SettingController@index')->name('settings.index');
        Route::put('/settings', 'SettingController@update')->name('settings.update');

        // Donasi Online
        Route::get('/donasi_online', 'DonlineController@index')->name('donasi_online.index');
        Route::get('/export_donasi', 'DonlineController@export')->name('export_donasi');

        // Donasi Manual
        Route::get('/donasi_manual', 'DonmanController@index')->name('donasi_manual.index');
        Route::get('/donasi_manual/{kode_donasi}', 'DonmanController@show')->name('donasi_manual.show');
        Route::delete('/donasi_manual/{kode_donasi}/delete', 'DonmanController@destroy')->name('donasi_manual.destroy');
        Route::put('/update_donasi/{kode_donasi}', 'DonmanController@change')->name('update_donasi.change');
        Route::get('/export_donasi2', 'DonmanController@export')->name('export_donasi2');

        // List Zakat
        Route::get('/list_zakat', 'ListzakatController@index')->name('list_zakat.index');
        Route::get('/list_zakat/{kode_zakat}', 'ListzakatController@show')->name('list_zakat.show');
        Route::delete('/list_zakat/{kode_zakat}/delete', 'ListzakatController@destroy')->name('list_zakat.destroy');
        Route::put('/update_zakat/{kode_zakat}', 'ListzakatController@change')->name('update_zakat.change');
        Route::get('/listzakat_export', 'ListzakatController@export')->name('export_listzakat');

        // Pesan
        Route::resource('/pesan', 'PesanController');

        // Kategori Berita
        Route::resource('/kategori_berita', 'KatberController');
        Route::post('/kategori_berita/aktif', 'KatberController@aktif')->name('katber.aktif');


        // Video
        Route::resource('/video', 'VideoController');
        Route::post('/video/aktif', 'VideoController@aktif')->name('video.aktif');

        // Tag
        Route::resource('/tag', 'TagController');
        Route::post('/tag/aktif', 'TagController@aktif')->name('tag.aktif');


        // Kategori Video
        Route::resource('/kategori_video', 'KatvidController');
        Route::post('/kategori_video/aktif', 'KatvidController@aktif')->name('katvid.aktif');

        // Kategori About
        Route::resource('/katbout', 'KatboutController');
        Route::post('/katbout/aktif', 'KatboutController@aktif')->name('katbout.aktif');

        // Mitra
        Route::resource('/mitra', 'MitraController');
        Route::post('/mitra/aktif', 'MitraController@aktif')->name('mitra.aktif');

        // Faqs
        Route::resource('/faqs', 'FaqsController');
        Route::post('/faqs/aktif', 'FaqsController@aktif')->name('faqs.aktif');

        // Agenda
        Route::resource('/agenda', 'AgendaController');
        Route::post('/agenda/aktif', 'AgendaController@aktif')->name('agenda.aktif');

        // Zakat
        Route::resource('/zakat', 'ZakatController');
        Route::post('/zakat/aktif', 'ZakatController@aktif')->name('zakat.aktif');

        // Zakat
        Route::resource('/sub-zakat', 'SubzakatController');
        Route::post('/sub-zakat/aktif', 'SubzakatController@aktif')->name('sub-zakat.aktif');

        // Slider
        Route::get('/slider/change', 'SliderController@change')->name('slider.change');
        Route::resource('/slider', 'SliderController');
        Route::post('/slider/aktif', 'SliderController@aktif')->name('slider.aktif');

        // Berita
        Route::post('/berita/upload', 'BeritaController@upload')->name('berita.upload');
        Route::resource('/berita', 'BeritaController');
        Route::post('/berita/aktif', 'BeritaController@aktif')->name('berita.aktif');

        // Jenis Donasi
        Route::resource('/jenis_donasi', 'JendonController');
        Route::post('/jenis_donasi/aktif', 'JendonController@aktif')->name('jenis_donasi.aktif');

        // Sub Donasi
        Route::resource('/sub_donasi', 'SubdonController');
        Route::post('/sub_donasi/aktif', 'SubdonController@aktif')->name('sub_donasi.aktif');

        // Album
        Route::get('/album/change', 'AlbumController@change')->name('album.change');
        Route::resource('/album', 'AlbumController');
        Route::post('/album/aktif', 'AlbumController@aktif')->name('album.aktif');

        // File
        Route::resource('/file', 'FileController');
        Route::post('/file/aktif', 'FileController@aktif')->name('file.aktif');

        // Foto
        Route::get('/gallery/{album_id}', 'GalleryController@index')->name('gallery.index');
        Route::get('/gallery/{album_id}/create', 'GalleryController@create')->name('gallery.create');
        Route::post('/gallery/{album_id}/create', 'GalleryController@store')->name('gallery.store');
        Route::get('/gallery/{album_id}/show', 'GalleryController@show')->name('gallery.show');
        Route::get('/gallery/{album_id}/edit/', 'GalleryController@edit')->name('gallery.edit');
        Route::put('/gallery/{id}', 'GalleryController@update')->name('gallery.update');
        Route::delete('/gallery/{id}', 'GalleryController@destroy')->name('gallery.destroy');
        Route::post('/gallery/aktif', 'GalleryController@aktif')->name('gallery.aktif');

        // Galeri
        // Route::resource('/gallery', 'GalleryController');
        // Route::post('/gallery/aktif', 'GalleryController@aktif')->name('gallery.aktif');

        // Kategori Produk
        Route::resource('/kategori_produk', 'KatproController');
        Route::resource('/produk', 'ProdukController');

        // Rekening
        Route::resource('/rekening', 'RekeningController');
        Route::post('/rekening/aktif', 'RekeningController@aktif')->name('rekening.aktif');
    });
});




// End

// My Test
Route::livewire('/task', 'task.index')->name('task.index');
Route::livewire('/task/create', 'task.create')->name('task.create');
Route::livewire('/task/edit/{id}', 'task.edit')->name('task.edit');

app/Http/Controllers/Admin/BeritaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Berita;
use App\Models\Katber;
use App\Models\Tag;
use Str;
use Auth;
use Storage;

class BeritaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
        $beritas = Berita::where('title', 'LIKE', "%$search%")->orderBy('id', 'desc')->paginate(10);
        $beritas->appends(['search' => $search]);
        return view('admin.beritas.index', compact('beritas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $katber = Katber::where('aktif', 'Y')->orderBy('id', 'desc')->get();
        $tags = Tag::get();
        return view('admin.beritas.add', compact('katber', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request;
        $request->validate([
            'judul' => 'required',
            'seo_judul' => 'required',
            'kategori' => 'required',
            'thumnail' => 'required|file|image|mimes:jpeg,png,jpg|max:2048',
            'deskripsi_gambar' => 'required',
            'content' => 'required',
            'deskripsi_meta' => 'required',
            'kutipan' => 'required',
        ]);

        $valid = Berita::where('title', '=', $request->judul)->count();
        if ($valid > 0) {
            return redirect()->route('admin.berita.index')->with('header', 'Gagal')->with('message', 'Gagal menambah Berita : ' . $request->judul . ' karena Berita ' . $request->judul . ' sudah ada')->with('Class', 'warning');
        } else {
            $image = $request->file('thumnail');
            $image_extension = $image->extension();
            $image_name = time() . "_" . $image->getClientOriginalName();
            $image->storeAs('/images/berita', $image_name, 'public');
            $create = Berita::create([
                'title' => $request->judul,
                'title_slug' => Str::slug($request->judul),
                'seo_judul' => $request->seo_judul,
                'kategori_id' => $request->kategori,
                'author_id' => Auth::user()->id,
                'thumnail' => $image_name,
                'deskripsi_gambar' => $request->deskripsi_gambar,
                'content' => $request->content,
                'deskripsi_meta' => $request->deskripsi_meta,
                'kutipan' => $request->kutipan,
            ]);
            if (isset($request->tag)) {
                $create->tag()->sync($request->tag);
            }
            return redirect()->route('admin.berita.index')->with('header', 'Sukses')->with('message', 'Berhasil menambah Berita : ' . $request->judul)->with('Class', 'success');
        }
    }

    public function posted(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);

        $valid = Katber::where('katber_name', '=', $request->name)->count();
        if ($valid > 0) {
            return redirect()->route('admin.berita.index')->with('header', 'Gagal')->with('message', 'Gagal menambah Kategori Berita : ' . $request->name . 'karena sudah ada')->with('Class', 'warning');
        } else {
            $create = Katber::create([
                'katber_name' => $request->name,
            ]);
            return redirect()->route('admin.berita.create')->with('header', 'Sukses')->with('message', 'Berhasil menambah Kategori Berita : ' . $request->name)->with('Class', 'success');
        }
    }

    public function upload(Request $request)
    {
        if ($request->hasFile('upload')) {
            $file = $request->file('upload');
            $fileName = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);

            $fileName = $fileName . '_' . time() . '.' . $file->getClientOriginalExtension();

            $file->move(public_path('uploads'), $fileName);

            $ckeditor = $request->input('CKEditorFuncNum');
            $url = asset('uploads/' . $fileName);
            $msg = 'Upload image sukses!';

            $response = "<script>window.parent.CKEDITOR.tools.callFunction($ckeditor, '$url', '$msg')</script>";

            @header('Content-type: text/html; charset=utf-8');
            return $response;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $beritas = Berita::findOrFail($id);
        return view('admin.beritas.show', compact('beritas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $beritas = Berita::findOrFail($id);
        $katber = Katber::where('aktif', 'Y')->orderBy('id', 'desc')->get();;
        $tags = Tag::get();
        return view('admin.beritas.edit', compact('beritas', 'katber', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => 'required|string',
            'seo_judul' => 'required',
            'kategori' => 'required',
            'thumnail' => 'nullable|file|image|mimes:jpeg,png,jpg|max:2048',
            'content' => 'required',
            'kutipan' => 'required',
        ]);

        $beritas = Berita::findOrFail($id);
        $beritas->title = $request->judul;
        $beritas->kategori_id = $request->kategori;
        $beritas->title_slug = Str::slug($request->judul);
        $beritas->seo_judul = $request->seo_judul;
        $beritas->content = $request->content;
        $beritas->deskripsi_meta = $request->deskripsi_meta;
        $beritas->kutipan = $request->kutipan;
        $beritas->deskripsi_gambar = $request->deskripsi_gambar;
        if ($request->hasFile('thumnail')) {
            Storage::delete('public/images/berita/' . $beritas->thumnail);
            $image = $request->file('thumnail');
            $image_extension = $image->extension();
            $image_name = time() . "_" . $image->getClientOriginalName();
            $image->storeAs('/images/berita', $image_name, 'public');
            $beritas->thumnail = $image_name;
        }
        $beritas->save();
        if (isset($request->tag)) {
            $beritas->tag()->sync($request->tag);
        }

        return redirect()->route('admin.berita.index')->with('header', 'Sukses')->with('message', 'Berhasil mengubah Berita : ' . $request->judul)->with('Class', 'success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $beritas = Berita::findOrFail($id);
        Storage::delete('public/images/berita/' . $beritas->thumnail);
        $beritas->delete();

        return redirect()->back()->with('header', 'Sukses')->with('message', 'Berhasil menghapus Berita')->with('Class', 'danger');
    }

    public function aktif(Request $request)
    {
        $id = $request->id;
        $mode = $request->mode;
        $beritas = Berita::find($id);
        if ($mode == "true") {
            $beritas->aktif = 'Y';
            // return 1;
        } elseif ($mode == "false") {
            $beritas->aktif = 'N';
            // return 2;
        }
        $beritas->update();

        return response()->json($beritas, 200);
    }
}

resources/views/admin/beritas/index.blade.php
@extends('layouts.app')

@push('style')
<!-- Plugins css -->
<link href="{{ asset('template/libs/sweet-alert2/sweetalert2.css')}}" rel="stylesheet">
@endpush
@section('title', 'Berita')

@section('content')
<div class="container-fluid">
    <div class='notifications top-right'></div>
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <h4 class="page-title">Manajemen Berita</h4>
            </div>
        </div>
    </div>
    <!-- end row -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group row">
                        <div class="col-12 col-md-6">
                            <a href="{{ route('admin.berita.create') }}" class="btn btn-info"><i
                                    class="fas fa-plus"></i> Tambah</a>
                            {{-- <a href="{{ route('admin.kategori_berita.index') }}" class="btn btn-success"><i
                                class="fas fa-plus"></i> Kategori Berita</a>
                            <a href="{{ route('admin.tag.index') }}" class="btn btn-secondary"><i
                                    class="fas fa-plus"></i> Tag Berita</a> --}}
                        </div>
                        <div class="col-12 col-md-6">
                            <form class="float-right form-inline" method="GET">
                                <input type="text" class="form-control mr-2" placeholder="Masukan Pencarian..."
                                    autocomplete="off" name='search'>
                                <button class="col btn btn-secondary" type="submit"><i
                                        class="fa fa-search"></i></button>
                            </form>
                        </div>
                    </div>

                    {{-- @if(session('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ session('success') }}
                </div>
                @endif
                @if(session('warning'))
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ session('warning') }}
                </div>
                @endif
                @if(session('danger'))
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ session('danger') }}
                </div>
                @endif --}}
                <div class="table-responsive">
                    <table class="table table-bordered table-striped mb-0 table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Judul Berita</th>
                                <th scope="col">Kategori</th>
                                <th scope="col" class="align-middle text-center">Thumbnail</th>
                                <th scope="col" class="align-middle text-center">Penulis</th>
                                <th scope="col" class="align-middle text-center">Aktif</th>
                                <th width="268" class="align-middle text-center">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($beritas as $index => $berita)
                            <tr>
                                <th scope="row" class="align-middle text-left">
                                    {{ $index+1+(($beritas->CurrentPage()-1)*$beritas->PerPage()) }}</th>
                                <td scope="row" class="align-middle text-left">{{ $berita->title }}</td>
                                <td scope="row" class="align-middle text-left">{{ $berita->kategori->katber_name }}</td>
                                <td scope="row" class="align-middle text-center"><img
                                        src="{{ Storage::url('images/berita/'.$berita->thumnail) }}"
                                        alt="{{ $berita->thumnail }}" srcset="" height="100"></td>
                                <td scope="row" class="align-middle text-center">{{ $berita->author->name }}</td>
                                <td scope="row" class="align-middle text-center">
                                    <form>
                                        <label class="switch" title="Aktif / Non-Aktif : berita">
                                            <input type="checkbox" name="toggle" class="aktifCheck" data-toggle="toggle"
                                                data-off="Disabled" data-target="{{$berita->id}}" data-on="Enabled"
                                                {{ $berita->aktif == "Y" ? 'checked' :'' }}>
                                    </form>
                                    <span class="slider round"></span>
                                    </label>
                                </td>
                                <td scope="row" class="align-middle text-center">
                                    <div class="d-inline-flex">
                                        <a href="{{ route('admin.berita.show', $berita->id) }}"
                                            class="btn btn-primary mr-2"><i class="fas fa-search"></i> Lihat</a>
                                        <a href="{{ route('admin.berita.edit', $berita->id) }}"
                                            class="btn btn-warning mr-2"><i class="fas fa-edit"></i> Edit</a>
                                        <form action="{{ route('admin.berita.destroy', $berita->id) }}" method="post">
                                            @csrf
                                            @method('delete')
                                            <button type="button" class="btn btn-danger btn-delete"><i
                                                    class="fas fa-trash"></i> Hapus</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="7">Daftar Post Tidak Ada</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="paginate float-right mt-3">
                    {{ $beritas->links() }}
                </div>
            </div>
        </div>

    </div> <!-- end col -->

</div> <!-- end row -->

</div> <!-- container-fluid -->
@endsection

@push('scripts')
<script>
    $('.aktifCheck').change(function () {
        var mode = $(this).prop('checked');
        var id = $(this).attr('data-target');
        var _token = "{{ csrf_token() }}";

        var dataHide = $(this).attr('data-hide');


        $.ajax({
            type: 'POST',
            dataType: 'JSON',
            url: "{{route('admin.berita.aktif')}}",
            data: {
                id: id,
                mode: mode,
                _token: _token
            },

            success: function (data) {


                if (mode) {
                    $(dataHide).css('display','block');
                } else {
                    $(dataHide).css("display","none");
                }
            }
        });


    });
</script>
<script src="{{ asset('template/libs/sweet-alert2/sweetalert2.min.js')}}"></script>
<script src="{{ asset('template/js/main.js') }}"></script>
@endpush

resources/views/admin/beritas/show.blade.php
@extends('layouts.app')

@section('title', 'Detail Berita')

@section('content')
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <h4 class="page-title">Detail Berita</h4>
            </div>
        </div>
    </div>
    <!-- end row -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card m-b-20">
                <div class="card-body">
                    @csrf
                    @method('put')
                    <div class="form-group row">
                        <label for="judul" class='col-md-2 col-form-label'>Judul</label>
                        <div class="col-md-10">
                            <input type="text" name="title" class='form-control @error('title') is-invalid @enderror' value="{{ $beritas->title }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="kutipan" class="col-md-2 col-form-label">Kutipan</label>
                        <div class="col-md-10">
                            <textarea name="kutipan" onkeyup="countChar(this)" class='form-control @error('kutipan') is-invalid @enderror' readonly>{{ $beritas->kutipan }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="kategori" class='col-md-2 col-form-label'>Kategori</label>
                        <div class="col-md-10">
                            <input type="text" name="stitle" class='form-control @error('stitle') is-invalid @enderror' value="{{ $beritas->kategori->katber_name }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="penulis" class='col-md-2 col-form-label'>Penulis</label>
                        <div class="col-md-10">
                            <input type="text" name="stitle" class='form-control @error('stitle') is-invalid @enderror' value="{{ $beritas->author->name }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="tanggal" class='col-md-2 col-form-label'>Tanggal</label>
                        <div class="col-md-10">
                            <input type="text" name="stitle" class='form-control @error('stitle') is-invalid @enderror' value="{{ \Carbon\Carbon::parse($beritas->created_at)->format('d, M Y H:i') }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="thumnail" class='col-md-2 col-form-label'>Thumbnail</label>
                        <div class="col-md-10">
                            <img src="{{ Storage::url('images/berita/'.$beritas->thumnail) }}" alt="" srcset="" style="width:200px">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="konten" class='col-md-2 col-form-label'>Kontent</label>
                        <div class="col-md-10">
                            {!! $beritas->content !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            <label for="tag_id" class=" form-control-label">Tag</label>
                        </div>
                        <div class="tags_add" >
                            <select class="select2 form-control" disabled name="tag[]" multiple="multiple">
                                @foreach($beritas->tag as $t)
                                <option value="{{$t->id}}">{{$t->nama_tag}}</option>
                                @endforeach 
                            </select>
                        </div>
                    </div>
                    <a href="{{ route('admin.berita.index') }}" class='btn-lg btn-outline-secondary float-right'>Kembali</a>
                </form>

            </div> 
        </div>

    </div> <!-- end col -->

</div> <!-- end row -->

</div> <!-- container-fluid -->
@endsection

@section('script')
<script>
    $(document).ready(function() {
        $('#kat').select2();
        CKEDITOR.replace('content', {
                    // filebrowserUploadUrl: "{{ route('admin.berita.upload', ['_token' => csrf_token() ]) }}",
                    // filebrowserUploadMethod: 'form'
                });
    });
    
    $(document).ready(function() {
        $('.select2').select2();
    });
</script>
@endsection