routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// if (env('APP_ENV') === 'production') {
//     URL::forceScheme('https');
// }

// Auth::routes();
Route::get('/hidden/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/hidden/login', 'Auth\LoginController@login');
Route::post('/hidden/logout', 'Auth\LoginController@logout')->name('logout');

// test
Route::get('/notifemaile', 'NotifController@test')->name('notifemaile');

// real
Route::get('/notifemail', 'NotifController@index')->name('notifemail');

Route::get('/', 'FrontendController@index')->name('main');
Route::get('/file/{id}/{slug}', 'FrontendController@download')->name('download');
Route::post('/pesan', 'FrontendController@store_pesan')->name('pesanstore');
Route::get('/berita', 'FrontendController@berita')->name('berita');
Route::get('/album', 'FrontendController@album')->name('album');
Route::get('/faq', 'FrontendController@faq')->name('faq');
Route::get('/kontak', 'FrontendController@kontak')->name('kontak');
Route::get('/rekening', 'FrontendController@rekening')->name('rekening');
Route::get('/detail_berita/{slug_title}', 'FrontendController@detailberita')->name('detail_berita');
Route::get('/kategori_berita/{katber_slug}', 'FrontendController@kategori')->name('kategori_berita');
Route::get('/detail_album/{album_slug}', 'FrontendController@detailalbum')->name('detail_album');
Route::get('/tentang-kami', 'FrontendController@tentangkami')->name('tentangkami');
Route::get('/detail_tentang/{katbout_slug}', 'FrontendController@detailtentang')->name('detail_tentang');
Route::post('/detail-donasi/confirm', 'FrontendController@detaildonasi')->name('detail-donasi');
Route::get('/status-donasi/{kode_donasi}', 'FrontendController@statusdonasi')->name('status-donasi');
Route::get('/cek-donasi', 'FrontendController@cekdonasi')->name('cek-donasi');
Route::put('/konfirmasi-donasi/{kode_donasi}', 'FrontendController@konfirmasidonasi')->name('konfirmasi-donasi');
Route::get('/list-donatur', 'FrontendController@listdonatur')->name('listdonatur');
Route::get('/manual-payment/{rekening_slug}', 'FrontendController@manualpembayaran')->name('manual-payment');

// Zakat
Route::get('/zakat', 'FrontendController@zakat')->name('zakat');

// Midtrans
Route::post('/finish', function () {
    return redirect()->route('/');
})->name('donasi.finish');

Route::post('/donasi/store', 'FrontendController@submit')->name('donasi.store');
Route::post('/zakat/store', 'FrontendController@submitzakat')->name('zakat.store');
Route::post('/notification/handler', 'FrontendController@notificationHandler')->name('notification.handler');

// AJAX
Route::post('/jenis_change', 'FrontendController@jenis')->name('front.jenis');

// Filemanager
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

// My Routes
Route::group(['namespace' => 'Admin',  'prefix' => 'hidden', 'middleware' => 'auth'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/', 'DashboardController@index')->name('home');

        // Account
        Route::get('/profil', 'AkunController@index')->name('profil.index');
        Route::put('/profil', 'AkunController@update')->name('profil.update');
        Route::resource('/manajemen_akun', 'ManukController');

        // Setting
        Route::get('/setting_zakat', 'SettingzakatController@index')->name('settingzakat.index');
        Route::put('/setting_zakat', 'SettingzakatController@update')->name('settingzakat.update');

        // Setting
        Route::get('/settings', 'SettingController@index')->name('settings.index');
        Route::put('/settings', 'SettingController@update')->name('settings.update');

        // Donasi Online
        Route::get('/donasi_online', 'DonlineController@index')->name('donasi_online.index');
        Route::get('/export_donasi', 'DonlineController@export')->name('export_donasi');

        // Donasi Manual
        Route::get('/donasi_manual', 'DonmanController@index')->name('donasi_manual.index');
        Route::get('/donasi_manual/{kode_donasi}', 'DonmanController@show')->name('donasi_manual.show');
        Route::delete('/donasi_manual/{kode_donasi}/delete', 'DonmanController@destroy')->name('donasi_manual.destroy');
        Route::put('/update_donasi/{kode_donasi}', 'DonmanController@change')->name('update_donasi.change');
        Route::get('/export_donasi2', 'DonmanController@export')->name('export_donasi2');

        // List Zakat
        Route::get('/list_zakat', 'ListzakatController@index')->name('list_zakat.index');
        Route::get('/list_zakat/{kode_zakat}', 'ListzakatController@show')->name('list_zakat.show');
        Route::delete('/list_zakat/{kode_zakat}/delete', 'ListzakatController@destroy')->name('list_zakat.destroy');
        Route::put('/update_zakat/{kode_zakat}', 'ListzakatController@change')->name('update_zakat.change');
        Route::get('/listzakat_export', 'ListzakatController@export')->name('export_listzakat');

        // Pesan
        Route::resource('/pesan', 'PesanController');

        // Kategori Berita
        Route::resource('/kategori_berita', 'KatberController');
        Route::post('/kategori_berita/aktif', 'KatberController@aktif')->name('katber.aktif');


        // Video
        Route::resource('/video', 'VideoController');
        Route::post('/video/aktif', 'VideoController@aktif')->name('video.aktif');

        // Tag
        Route::resource('/tag', 'TagController');
        Route::post('/tag/aktif', 'TagController@aktif')->name('tag.aktif');


        // Kategori Video
        Route::resource('/kategori_video', 'KatvidController');
        Route::post('/kategori_video/aktif', 'KatvidController@aktif')->name('katvid.aktif');

        // Kategori About
        Route::resource('/katbout', 'KatboutController');
        Route::post('/katbout/aktif', 'KatboutController@aktif')->name('katbout.aktif');

        // Mitra
        Route::resource('/mitra', 'MitraController');
        Route::post('/mitra/aktif', 'MitraController@aktif')->name('mitra.aktif');

        // Faqs
        Route::resource('/faqs', 'FaqsController');
        Route::post('/faqs/aktif', 'FaqsController@aktif')->name('faqs.aktif');

        // Agenda
        Route::resource('/agenda', 'AgendaController');
        Route::post('/agenda/aktif', 'AgendaController@aktif')->name('agenda.aktif');

        // Zakat
        Route::resource('/zakat', 'ZakatController');
        Route::post('/zakat/aktif', 'ZakatController@aktif')->name('zakat.aktif');

        // Zakat
        Route::resource('/sub-zakat', 'SubzakatController');
        Route::post('/sub-zakat/aktif', 'SubzakatController@aktif')->name('sub-zakat.aktif');

        // Slider
        Route::get('/slider/change', 'SliderController@change')->name('slider.change');
        Route::resource('/slider', 'SliderController');
        Route::post('/slider/aktif', 'SliderController@aktif')->name('slider.aktif');

        // Berita
        Route::post('/berita/upload', 'BeritaController@upload')->name('berita.upload');
        Route::resource('/berita', 'BeritaController');
        Route::post('/berita/aktif', 'BeritaController@aktif')->name('berita.aktif');

        // Jenis Donasi
        Route::resource('/jenis_donasi', 'JendonController');
        Route::post('/jenis_donasi/aktif', 'JendonController@aktif')->name('jenis_donasi.aktif');

        // Sub Donasi
        Route::resource('/sub_donasi', 'SubdonController');
        Route::post('/sub_donasi/aktif', 'SubdonController@aktif')->name('sub_donasi.aktif');

        // Album
        Route::get('/album/change', 'AlbumController@change')->name('album.change');
        Route::resource('/album', 'AlbumController');
        Route::post('/album/aktif', 'AlbumController@aktif')->name('album.aktif');

        // File
        Route::resource('/file', 'FileController');
        Route::post('/file/aktif', 'FileController@aktif')->name('file.aktif');

        // Foto
        Route::get('/gallery/{album_id}', 'GalleryController@index')->name('gallery.index');
        Route::get('/gallery/{album_id}/create', 'GalleryController@create')->name('gallery.create');
        Route::post('/gallery/{album_id}/create', 'GalleryController@store')->name('gallery.store');
        Route::get('/gallery/{album_id}/show', 'GalleryController@show')->name('gallery.show');
        Route::get('/gallery/{album_id}/edit/', 'GalleryController@edit')->name('gallery.edit');
        Route::put('/gallery/{id}', 'GalleryController@update')->name('gallery.update');
        Route::delete('/gallery/{id}', 'GalleryController@destroy')->name('gallery.destroy');
        Route::post('/gallery/aktif', 'GalleryController@aktif')->name('gallery.aktif');

        // Galeri
        // Route::resource('/gallery', 'GalleryController');
        // Route::post('/gallery/aktif', 'GalleryController@aktif')->name('gallery.aktif');

        // Kategori Produk
        Route::resource('/kategori_produk', 'KatproController');
        Route::resource('/produk', 'ProdukController');

        // Rekening
        Route::resource('/rekening', 'RekeningController');
        Route::post('/rekening/aktif', 'RekeningController@aktif')->name('rekening.aktif');
    });
});




// End

// My Test
Route::livewire('/task', 'task.index')->name('task.index');
Route::livewire('/task/create', 'task.create')->name('task.create');
Route::livewire('/task/edit/{id}', 'task.edit')->name('task.edit');

app/Models/Subzakat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Subzakat extends Model
{
    protected $table = 'sub_zakat';

    protected $fillable = ['nama_sub_zakat', 'zakat_id'];

    public function zakat() {
        return $this->belongsTo('App\Models\Zakat', 'zakat_id');
    }
}

app/Http/Controllers/Admin/SubzakatController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Zakat;
use App\Models\Subzakat;

class SubzakatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
        $subzakats = Subzakat::where('nama_sub_zakat', 'LIKE',"%$search%")->orderBy('id','desc')->paginate(10);
        $subzakats->appends(['search' => $search]);
        return view('admin.sub_zakat.index', compact('subzakats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $zakats = Zakat::where('aktif','Y')->orderBy('id','desc')->get();
        return view('admin.sub_zakat.add', compact('zakats'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'zakat' => 'required',
        ]);

        $valid = Subzakat::where('nama_sub_zakat', '=', $request->name)->count();
        if($valid > 0) {
            return redirect()->route('admin.sub-zakat.index')->with('header', 'Gagal')->with('message', 'Gagal menambah Sub Zakat : ' . $request->name . ' karena Sub Zakat ' . $request->name . ' sudah ada')->with('Class', 'warning');
        } else {
            $create = Subzakat::create([
                'zakat_id' => $request->zakat,
                'nama_sub_zakat' => $request->name,
                'rumus_pertama' => $request->rumus_pertama,
                'rumus_kedua' => $request->rumus_kedua,
                'rumus_ketiga' => $request->rumus_ketiga,
            ]);
            return redirect()->route('admin.sub-zakat.index')->with('header', 'Sukses')->with('message', 'Sukses menambah Sub Zakat : ' . $request->name)->with('Class', 'success');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subzakats = Subzakat::findOrFail($id);
        $zakats = Zakat::where('aktif','Y')->orderBy('id','desc')->get();
        return view('admin.sub_zakat.edit', compact('subzakats', 'zakats'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'zakat' => 'required',
        ]);

        $create = Subzakat::find($id)->update([
            'zakat_id' => $request->zakat,
            'nama_sub_zakat' => $request->name,
            'rumus_pertama' => $request->rumus_pertama,
            'rumus_kedua' => $request->rumus_kedua,
            'rumus_ketiga' => $request->rumus_ketiga,
        ]);
        return redirect()->route('admin.sub-zakat.index')->with('header', 'Sukses')->with('message', 'Sukses mengubah Sub Donasi : ' . $request->name)->with('Class', 'success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subzakat = Subzakat::findOrFail($id);
        $subzakat->delete();
        return redirect()->back()->with('header', 'Sukses')->with('message', 'Sukses menghapus Sub Zakat')->with('Class', 'success');
    }

    public function aktif(Request $request)
    {
        $id = $request->id;
        $mode = $request->mode;
        $subzakat = Subzakat::find($id);
        if ($mode == "true") {
            $subzakat->aktif = 'Y';
            // return 1;
        } elseif ($mode == "false") {
            $subzakat->aktif = 'N';
            // return 2;
        }
        $subzakat->update();

        return response()->json($subzakat, 200);
    }
}

resources/views/admin/sub_zakat/add.blade.php
@extends('layouts.app')

@section('title', 'Tambah Sub Zakat')

@section('content')
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <h4 class="page-title">Tambah Sub Zakat</h4>
            </div>
        </div>
    </div>
    <!-- end row -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card m-b-20">
                <div class="card-body">
                    <form action="{{ route('admin.sub-zakat.store') }}" method="POST">
                        @csrf
                        <div class="form-group row">
                            <label for="" class='col-md-2 col-form-label'>Nama Zakat</label>
                            <div class="col-md-10">
                                <select class="form-control @error('zakat') is-invalid @enderror" name="zakat" id="asd" required>
                                    <option value="">-- Pilih Jenis Zakat --</option>
                                    @foreach ($zakats as $zakat)
                                    <option value="{{ $zakat->id }}">{{ $zakat->nama_zakat }}</option>
                                    @endforeach
                                </select>
                                @error('zakat')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class='col-md-2 col-form-label'>Nama Sub Zakat</label>
                            <div class="col-md-10">
                                <input type="text" name="name" class='form-control @error('name') is-invalid @enderror'>
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <button type="submit" class='btn-lg btn-primary float-right'>Tambah</button>
                        <a href="{{ route('admin.sub-zakat.index') }}" class="btn-lg btn-outline-secondary float-right mr-2">Kembali</a>                          
                    </form>

                </div>
            </div>

        </div> <!-- end col -->

    </div> <!-- end row -->

</div> <!-- container-fluid -->
@endsection

@push('scripts')
<script>
    $(document).ready(function() {
        $('#asd').select2();
    });
</script>
<script src="{{asset('template/libs/select2/js/select2.min.js')}}"></script>
<script src="{{asset('template/libs/admin-resources/bootstrap-filestyle/bootstrap-filestyle.min.js')}}"></script>
@endpush

resources/views/admin/sub_zakat/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Sub Zakat')

@section('content')
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <h4 class="page-title">Edit Sub Zakat</h4>
            </div>
        </div>
    </div>
    <!-- end row -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card m-b-20">
                <div class="card-body">
                    <form action="{{ route('admin.sub-zakat.update', $subzakats->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="form-group row">
                            <label for="" class='col-md-2 col-form-label'>Jenis Zakat</label>
                            <div class="col-md-10">
                                <select class="form-control @error('zakat') is-invalid @enderror kat" name="zakat" id="kat" required>
                                    <option value="">-- Pilih Zakat --</option>
                                    @foreach ($zakats as $zakat)
                                    <option value="{{ $zakat->id }}" <?php if($subzakats->zakat_id == $zakat->id) { echo "selected";} ?>>{{ $zakat->nama_zakat }}</option>
                                    @endforeach
                                </select>
                                @error('zakat')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="" class='col-md-2 col-form-label'>Nama Sub Zakat</label>
                            <div class="col-md-10">
                                <input type="text" name="name" class='form-control @error('name') is-invalid @enderror' value="{{ $subzakats->nama_sub_zakat }}">
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <button type="submit" class='btn-lg btn-primary float-right'>Tambah</button>
                        <a href="{{ route('admin.sub-zakat.index') }}" class="btn-lg btn-outline-secondary float-right mr-2">Kembali</a>                               
                    </form>
                </div>
            </div>
        </div> 
    </div> 
</div>
@endsection

@push('scripts')
<script>
    $(document).ready(function() {
        $('.kat').select2();
    });
</script>
<script src="{{asset('template/libs/select2/js/select2.min.js')}}"></script>
<script src="{{asset('template/libs/admin-resources/bootstrap-filestyle/bootstrap-filestyle.min.js')}}"></script>
@endpush

resources/views/admin/sub_zakat/index.blade.php
@extends('layouts.app')

@push('style')
<!-- Plugins css -->
<link href="{{ asset('template/libs/sweet-alert2/sweetalert2.css')}}" rel="stylesheet">
@endpush
@section('title', 'Sub Zakat')

@section('content')
<div class="container-fluid">
    <div class='notifications top-right'></div>
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <h4 class="page-title">Manajemen Sub Zakat</h4>
            </div>
        </div>
    </div>
    <!-- end row -->

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                  <div class="form-group row">
                    <div class="col">
                        <a href="{{ route('admin.sub-zakat.create') }}" class="btn btn-info"><i class="fas fa-plus"></i> Tambah</a>
                        <a href="{{ route('admin.zakat.index') }}" class="btn btn-outline-success"><i class="fas fa-arrow-left"></i> Kembali</a>
                    </div>
                    <div class="col">
                        <form class="float-right form-inline" method="GET">
                            <input type="text" class="form-control mr-2" placeholder="Masukan Pencarian..." autocomplete="off" name='search'>
                            <button class="btn btn-secondary" type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-bordered table-striped mb-0 table-hover">
                        <thead>
                            <tr>
                             <th scope="col">#</th>
                             <th scope="col">Nama Sub Zakat</th>
                             <th scope="col">Nama Zakat</th>
                             <th scope="col" class="align-middle text-center">Aktif</th>
                             <th width="185" scope="col" class="align-middle text-center">Aksi</th>
                         </tr>
                     </thead>
                     <tbody>
                        @forelse ($subzakats as $index => $subzakat)

                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td scope="row">{{ $subzakat->nama_sub_zakat }}</td>
                            <td scope="row">{{ $subzakat->zakat->nama_zakat }}</td>
                            <td scope="row" class="align-middle text-center">
                                <form> 
                                    <label class="switch" title="Aktif / Non-Aktif : Sub Zakat"> 
                                        <input type="checkbox" name="toggle" class="aktifCheck" data-toggle="toggle" data-off="Disabled"  data-target="{{$subzakat->id}}" data-on="Enabled" {{ $subzakat->aktif == "Y" ? 'checked' :'' }}>
                                    </form>
                                    <span class="slider round"></span>
                                </label>
                            </td>
                            <td scope="row" class="align-middle text-center">
                                <div class='d-inline-flex'>
                                    <a href="{{ route('admin.sub-zakat.edit', $subzakat->id) }}" class='btn btn-warning mr-2'><i class="fas fa-edit"></i> Edit</a>
                                    <form action="{{ route('admin.sub-zakat.destroy', $subzakat->id) }}" method="post">
                                        <form action="{{ route('admin.sub-zakat.destroy', $subzakat->id) }}" method="post">
                                            @csrf
                                            @method('delete')
                                            <button type="button" class='btn btn-danger btn-delete'><i class="fas fa-trash"></i> Hapus</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="5">Daftar Sub Zakat Tidak Ada</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="paginate float-right mt-3">
                   {{$subzakats->links()}}
               </div>
           </div>
       </div>

   </div> <!-- end col -->

</div> <!-- end row -->

</div> <!-- container-fluid -->
@endsection

@push('scripts')
<script>
    $('.aktifCheck').change(function () {
        var mode = $(this).prop('checked');
        var id = $(this).attr('data-target');
        var _token = "{{ csrf_token() }}";

        var dataHide = $(this).attr('data-hide');


        $.ajax({
            type: 'POST',
            dataType: 'JSON',
            url: "{{route('admin.sub-zakat.aktif')}}",
            data: {
                id: id,
                mode: mode,
                _token: _token
            },

            success: function (data) {


                if (mode) {
                    $(dataHide).css('display','block');
                } else {
                    $(dataHide).css("display","none");
                }
            }
        });


    });
</script>
<script src="{{ asset('template/libs/sweet-alert2/sweetalert2.min.js')}}"></script>
<script src="{{ asset('template/js/main.js') }}"></script>
@endpush